name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src
    
    - name: Prepare GitHub registry
      with: 
        source-url: https://nuget.pkg.github.com/watertrans/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Push generated package to GitHub registry
      run: dotnet nuget push "WaterTrans.GlyphLoader/bin/Release/WaterTrans.GlyphLoader.*.nupkg" --skip-duplicate --no-symbols true
      working-directory: ./src


